### PR TITLE
Add git attributes for smaller download size

### PR DESCRIPTION
**Pull request by stchr**
Excluding /design, /docs and /tests

### CODE REVIEW

**Comment by derickr** [comment]
What does this export-ignore do? Certainly when you clone you should get the whole repo?

**Comment by stchr** [comment]
Please see http://git-scm.com/docs/git-fast-export

It is useful for generating Archives for e.g. composer. See discussion and solutions (export-ignore is the prefered one) on https://github.com/composer/composer/issues/1750

**Comment by stchr** [comment]
Sorry for commit a6b2279 in this PR. Should go in another PR, but can be merged with this one if you don't mind.

**Comment by stchr** [comment]
Any updates on this?

**Comment by derickr** [comment]
I don't think this is a good idea. I would also like to refer to https://github.com/composer/composer/issues/1750#issuecomment-15710068 and the fact that https://github.com/composer/composer/issues/1750 has been closed as "Won't fix"

**Pull request closed without merging**
